package sjj.fiction

val DISPOSABLE_READ_INDEX = "DISPOSABLE_READ_INDEX"
val DISPOSABLE_CACHED_BOOK_CHAPTER = "DISPOSABLE_CACHED_BOOK_CHAPTER"
val DISPOSABLE_ACTIVITY_READ_READ_INDEX = "DISPOSABLE_ACTIVITY_READ_READ_INDEX"
val DISPOSABLE_ACTIVITY_DETAILS_REFRESH = "DISPOSABLE_ACTIVITY_DETAILS_REFRESH"
val DISPOSABLE_ACTIVITY_MAIN_REFRESH = "DISPOSABLE_ACTIVITY_MAIN_REFRESH"